package com.mikori.kids.core.ui.theme

import androidx.compose.ui.graphics.Color

// Marca
val Matcha = Color(0xFF4F7A5B)
val MatchaLight = Color(0xFFCDE7CE)
val Sakura = Color(0xFFB06E7E)
val SakuraLight = Color(0xFFF6DCE2)
val Sky = Color(0xFF6B84B0)
val Lavender = Color(0xFF8E88C4)
val Washi = Color(0xFFFBF7F0)
val Ink = Color(0xFF2B2A27)

// Light
val LightPrimary = Color(0xFF4F7A5B)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFCDE7CE)
val LightOnPrimaryContainer = Color(0xFF0C2914)
val LightSecondary = Color(0xFFB06E7E)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFF6DCE2)
val LightOnSecondaryContainer = Color(0xFF3A1721)
val LightTertiary = Color(0xFF6B84B0)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFFBF7F0)
val LightOnBackground = Color(0xFF2B2A27)
val LightSurface = Color(0xFFFFFDF9)
val LightOnSurface = Color(0xFF2B2A27)
val LightSurfaceVariant = Color(0xFFEFE7DA)
val LightOnSurfaceVariant = Color(0xFF4E4A42)
val LightOutline = Color(0xFFC9BFAE)
val LightError = Color(0xFFB3261E)
val LightTextSecondary = Color(0xFF6E6A61)

// Dark (noche japonesa + lavanda)
val DarkPrimary = Color(0xFFA6CBA0)
val DarkOnPrimary = Color(0xFF10321A)
val DarkPrimaryContainer = Color(0xFF35563B)
val DarkOnPrimaryContainer = Color(0xFFC3E7BE)
val DarkSecondary = Color(0xFFE6B4C0)
val DarkOnSecondary = Color(0xFF43222C)
val DarkTertiary = Color(0xFFB7C2E8)
val DarkBackground = Color(0xFF14141A)
val DarkOnBackground = Color(0xFFE7E3DA)
val DarkSurface = Color(0xFF1C1C24)
val DarkOnSurface = Color(0xFFE7E3DA)
val DarkSurfaceVariant = Color(0xFF2A2A33)
val DarkOnSurfaceVariant = Color(0xFFC9C4BC)
val DarkOutline = Color(0xFF47444E)
val DarkError = Color(0xFFF2B8B5)
val DarkTextSecondary = Color(0xFFB4AFA5)
